services:
  order-service:
    build: ./mock-ecosystem/order-service-go
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    networks:
      - syslog-network

  shipping-service:
    build: ./mock-ecosystem/shipping-service-python
    ports:
      - "8091-8093:8082"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.15'
          memory: 64M
    networks:
      - syslog-network

  auth-service:
    build: ./mock-ecosystem/auth-service-java
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      - syslog-network

  syswatch-agent:
    build: ./syswatch-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    networks:
      - syslog-network

networks:
  syslog-network:
    driver: bridge
