services:
  # 1. Order Service (Go)
  order-service:
    build: ./mock-ecosystem/order-service-go
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    networks:
      - syslog-network

  # 2. Shipping Service (FastAPI)
  shipping-service:
    build: ./mock-ecosystem/shipping-service-python
    ports:
      - "8091-8093:8082"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.15'
          memory: 64M
    networks:
      - syslog-network

  # 3. Auth Service (Java)
  auth-service:
    build: ./mock-ecosystem/auth-service-java
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      - syslog-network

  # 4. TRÁI TIM HỆ THỐNG: SysWatch Agent (Go)
  syswatch-agent:
  build: ./syswatch-agent
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped    networks:
      - syslog-network

networks:
  syslog-network:
    driver: bridge
